//! Guest program template - creates complete RISC Zero guest program

use crate::dsl::BusinessRulesDSL;
use anyhow::Result;

/// Create a complete guest program by combining types, validations, and template
pub fn create_guest_program(
    dsl: &BusinessRulesDSL,
    types_code: &str,
    validation_code: &str,
) -> Result<String> {
    let use_case = &dsl.use_case;
    let description = &dsl.description;
    let helper_functions = super::validation_gen::generate_helper_functions();

    let program = format!(
        r#"//! Guest program for: {use_case}
//! {description}
//!
//! This code was automatically generated from a Business Rules DSL.
//! It runs inside the RISC Zero zkVM to verify business logic while
//! keeping private data hidden.

#![no_main]

use risc0_zkvm::guest::env;

{types_code}

{helper_functions}

{validation_code}

/// Main entry point for the guest program
fn main() {{
    // Read private inputs
    let private_inputs: PrivateInputs = env::read();

    // Read public parameters
    let public_params: PublicParams = env::read();

    // Perform all validation checks
    let compliance_result = validate_all(&private_inputs, &public_params);

    // Create output
    let outputs = Outputs {{
        compliance_result,
        // TODO: Add any additional output fields from DSL
    }};

    // Commit output to the journal (this becomes the public output of the proof)
    env::commit(&outputs);
}}
"#,
        use_case = use_case,
        description = description,
        types_code = types_code,
        helper_functions = helper_functions,
        validation_code = validation_code,
    );

    Ok(program)
}

/// Create a README for the generated SDK
pub fn create_sdk_readme(dsl: &BusinessRulesDSL) -> String {
    format!(
        r#"# {} SDK

## Overview

This SDK was automatically generated from a Business Rules DSL specification.

**Use Case:** {}
**Description:** {}
**Version:** {}

## Generated Components

- `methods/guest/src/main.rs` - RISC Zero guest program (runs in zkVM)
- `methods/build.rs` - Build script that compiles the guest program
- `methods/Cargo.toml` - Dependencies for the methods crate

## Validation Rules

This SDK enforces the following validation rules:

{}

## Usage

### 1. Build the guest program

```bash
cd methods
cargo build --release
```

### 2. Generate a proof

```rust
use risc0_zkvm::{{default_prover, ExecutorEnv}};

// Prepare inputs
let private_inputs = PrivateInputs {{ /* ... */ }};
let public_params = PublicParams {{ /* ... */ }};

// Build executor environment
let env = ExecutorEnv::builder()
    .write(&private_inputs)?
    .write(&public_params)?
    .build()?;

// Generate proof
let prover = default_prover();
let receipt = prover.prove(env, GUEST_ELF)?;

// Extract outputs
let outputs: Outputs = receipt.journal.decode()?;
println!("Compliance result: {{}}", outputs.compliance_result);
```

## Integration

Integrate this SDK into your application to generate zero-knowledge proofs
that validate business logic without revealing private data.

---

*Generated by Khafi Gateway Logic Compiler*
"#,
        dsl.use_case,
        dsl.use_case,
        dsl.description,
        dsl.version,
        format_validation_rules(dsl)
    )
}

fn format_validation_rules(dsl: &BusinessRulesDSL) -> String {
    dsl.validation_rules
        .iter()
        .enumerate()
        .map(|(idx, rule)| {
            format!(
                "{}. **{}**: {}",
                idx + 1,
                rule.rule_type(),
                rule.description()
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::DslParser;

    #[test]
    fn test_create_guest_program() {
        let dsl = DslParser::parse_file("../../docs/examples/age-verification-simple.json")
            .expect("Failed to parse DSL");

        let types = "struct PrivateInputs {}\nstruct PublicParams {}\nstruct Outputs {}";
        let validation = "fn validate_all() -> bool { true }";

        let program =
            create_guest_program(&dsl, types, validation).expect("Failed to create guest program");

        // Verify program structure
        assert!(program.contains("#![no_main]"));
        assert!(program.contains("use risc0_zkvm::guest::env"));
        assert!(program.contains("fn main()"));
        assert!(program.contains("env::read()"));
        assert!(program.contains("env::commit"));
        assert!(program.contains(&dsl.use_case));
    }

    #[test]
    fn test_create_sdk_readme() {
        let dsl = DslParser::parse_file("../../docs/examples/age-verification-simple.json")
            .expect("Failed to parse DSL");

        let readme = create_sdk_readme(&dsl);

        assert!(readme.contains(&dsl.use_case));
        assert!(readme.contains("Overview"));
        assert!(readme.contains("Usage"));
        assert!(readme.contains("Validation Rules"));
    }
}
